"""Изменил поля в модели Item

Revision ID: 866c47c3758d
Revises: e02170351a18
Create Date: 2026-01-23 10:16:36.773111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866c47c3758d'
down_revision: Union[str, Sequence[str], None] = 'e02170351a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('id_item', sa.String(length=36), nullable=True))
    op.add_column('item', sa.Column('sid', sa.String(length=36), nullable=True))
    op.add_column('item', sa.Column('balance', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('stuff', sa.String(length=100), nullable=True))
    op.add_column('item', sa.Column('category_id', sa.String(length=36), nullable=True))
    op.add_column('item', sa.Column('photoUrl', sa.String(length=500), nullable=True))
    op.add_column('item', sa.Column('image_title', sa.String(length=150), nullable=True))
    op.drop_index(op.f('ix_item_source_id'), table_name='item')
    op.drop_column('item', 'category')
    op.drop_column('item', 'image_url')
    op.drop_column('item', 'stock')
    op.drop_column('item', 'source_id')
    op.drop_column('item', 'is_active')
    op.drop_column('item', 'brand')
    op.drop_column('item', 'original_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('original_price', sa.FLOAT(), nullable=True))
    op.add_column('item', sa.Column('brand', sa.VARCHAR(length=100), nullable=True))
    op.add_column('item', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('item', sa.Column('source_id', sa.INTEGER(), nullable=True))
    op.add_column('item', sa.Column('stock', sa.INTEGER(), nullable=True))
    op.add_column('item', sa.Column('image_url', sa.VARCHAR(length=500), nullable=True))
    op.add_column('item', sa.Column('category', sa.VARCHAR(length=150), nullable=True))
    op.create_index(op.f('ix_item_source_id'), 'item', ['source_id'], unique=False)
    op.drop_column('item', 'image_title')
    op.drop_column('item', 'photoUrl')
    op.drop_column('item', 'category_id')
    op.drop_column('item', 'stuff')
    op.drop_column('item', 'balance')
    op.drop_column('item', 'sid')
    op.drop_column('item', 'id_item')
    # ### end Alembic commands ###
